// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.6.5. SEE SOURCE BELOW. !!
pragma solidity >=0.7.0 <0.9.0;

interface IStargateFarm {
    event Add(uint256 allocPoint, address indexed lpToken);
    event Deposit(address indexed user, uint256 indexed pid, uint256 amount);
    event EmergencyWithdraw(
        address indexed user,
        uint256 indexed pid,
        uint256 amount
    );
    event OwnershipTransferred(
        address indexed previousOwner,
        address indexed newOwner
    );
    event Set(uint256 indexed pid, uint256 allocPoint);
    event TokensPerSec(uint256 eTokenPerSecond);
    event Withdraw(address indexed user, uint256 indexed pid, uint256 amount);

    function BONUS_MULTIPLIER() external view returns (uint256);

    function add(uint256 _allocPoint, address _lpToken) external;

    function bonusEndTime() external view returns (uint256);

    function deposit(uint256 _pid, uint256 _amount) external;

    function eToken() external view returns (address);

    function eTokenPerSecond() external view returns (uint256);

    function emergencyWithdraw(uint256 _pid) external;

    function getMultiplier(uint256 _from, uint256 _to)
    external
    view
    returns (uint256);

    function lpBalances(uint256) external view returns (uint256);

    function massUpdatePools() external;

    function owner() external view returns (address);

    function pendingEmissionToken(uint256 _pid, address _user)
    external
    view
    returns (uint256);

    function poolInfo(uint256)
    external
    view
    returns (
        address lpToken,
        uint256 allocPoint,
        uint256 lastRewardTime,
        uint256 accEmissionPerShare
    );

    function poolLength() external view returns (uint256);

    function renounceOwnership() external;

    function set(uint256 _pid, uint256 _allocPoint) external;

    function setETokenPerSecond(uint256 _eTokenPerSecond) external;

    function startTime() external view returns (uint256);

    function totalAllocPoint() external view returns (uint256);

    function transferOwnership(address newOwner) external;

    function updatePool(uint256 _pid) external;

    function userInfo(uint256, address)
    external
    view
    returns (uint256 amount, uint256 rewardDebt);

    function withdraw(uint256 _pid, uint256 _amount) external;
}

interface IStargateRouterMaster {
    event CachedSwapSaved(
        uint16 chainId,
        bytes srcAddress,
        uint256 nonce,
        address token,
        uint256 amountLD,
        address to,
        bytes payload,
        bytes reason
    );
    event OwnershipTransferred(
        address indexed previousOwner,
        address indexed newOwner
    );
    event RedeemLocalCallback(
        uint16 srcChainId,
        bytes indexed srcAddress,
        uint256 indexed nonce,
        uint256 srcPoolId,
        uint256 dstPoolId,
        address to,
        uint256 amountSD,
        uint256 mintAmountSD
    );
    event Revert(
        uint8 bridgeFunctionType,
        uint16 chainId,
        bytes srcAddress,
        uint256 nonce
    );
    event RevertRedeemLocal(
        uint16 srcChainId,
        uint256 _srcPoolId,
        uint256 _dstPoolId,
        bytes to,
        uint256 redeemAmountSD,
        uint256 mintAmountSD,
        uint256 indexed nonce,
        bytes indexed srcAddress
    );

    function activateChainPath(
        uint256 _poolId,
        uint16 _dstChainId,
        uint256 _dstPoolId
    ) external;

    function addLiquidity(
        uint256 _poolId,
        uint256 _amountLD,
        address _to
    ) external;

    function bridge() external view returns (address);

    function cachedSwapLookup(
        uint16,
        bytes memory,
        uint256
    )
    external
    view
    returns (
        address token,
        uint256 amountLD,
        address to,
        bytes memory payload
    );

    function callDelta(uint256 _poolId, bool _fullMode) external;

    function clearCachedSwap(
        uint16 _srcChainId,
        bytes memory _srcAddress,
        uint256 _nonce
    ) external;

    function createChainPath(
        uint256 _poolId,
        uint16 _dstChainId,
        uint256 _dstPoolId,
        uint256 _weight
    ) external;

    function createPool(
        uint256 _poolId,
        address _token,
        uint8 _sharedDecimals,
        uint8 _localDecimals,
        string memory _name,
        string memory _symbol
    ) external returns (address);

    function creditChainPath(
        uint16 _dstChainId,
        uint256 _dstPoolId,
        uint256 _srcPoolId,
        Pool.CreditObj memory _c
    ) external;

    function factory() external view returns (address);

    function instantRedeemLocal(
        uint16 _srcPoolId,
        uint256 _amountLP,
        address _to
    ) external returns (uint256 amountSD);

    function mintFeeOwner() external view returns (address);

    function owner() external view returns (address);

    function protocolFeeOwner() external view returns (address);

    function quoteLayerZeroFee(
        uint16 _dstChainId,
        uint8 _functionType,
        bytes memory _toAddress,
        bytes memory _transferAndCallPayload,
        IStargateRouter.lzTxObj memory _lzTxParams
    ) external view returns (uint256, uint256);

    function redeemLocal(
        uint16 _dstChainId,
        uint256 _srcPoolId,
        uint256 _dstPoolId,
        address _refundAddress,
        uint256 _amountLP,
        bytes memory _to,
        IStargateRouter.lzTxObj memory _lzTxParams
    ) external payable;

    function redeemLocalCallback(
        uint16 _srcChainId,
        bytes memory _srcAddress,
        uint256 _nonce,
        uint256 _srcPoolId,
        uint256 _dstPoolId,
        address _to,
        uint256 _amountSD,
        uint256 _mintAmountSD
    ) external;

    function redeemLocalCheckOnRemote(
        uint16 _srcChainId,
        bytes memory _srcAddress,
        uint256 _nonce,
        uint256 _srcPoolId,
        uint256 _dstPoolId,
        uint256 _amountSD,
        bytes memory _to
    ) external;

    function redeemRemote(
        uint16 _dstChainId,
        uint256 _srcPoolId,
        uint256 _dstPoolId,
        address _refundAddress,
        uint256 _amountLP,
        uint256 _minAmountLD,
        bytes memory _to,
        IStargateRouter.lzTxObj memory _lzTxParams
    ) external payable;

    function renounceOwnership() external;

    function retryRevert(
        uint16 _srcChainId,
        bytes memory _srcAddress,
        uint256 _nonce
    ) external payable;

    function revertLookup(
        uint16,
        bytes memory,
        uint256
    ) external view returns (bytes memory);

    function revertRedeemLocal(
        uint16 _dstChainId,
        bytes memory _srcAddress,
        uint256 _nonce,
        address _refundAddress,
        IStargateRouter.lzTxObj memory _lzTxParams
    ) external payable;

    function sendCredits(
        uint16 _dstChainId,
        uint256 _srcPoolId,
        uint256 _dstPoolId,
        address _refundAddress
    ) external payable;

    function setBridgeAndFactory(address _bridge, address _factory) external;

    function setDeltaParam(
        uint256 _poolId,
        bool _batched,
        uint256 _swapDeltaBP,
        uint256 _lpDeltaBP,
        bool _defaultSwapMode,
        bool _defaultLPMode
    ) external;

    function setFeeLibrary(uint256 _poolId, address _feeLibraryAddr) external;

    function setFees(uint256 _poolId, uint256 _mintFeeBP) external;

    function setMintFeeOwner(address _owner) external;

    function setProtocolFeeOwner(address _owner) external;

    function setSwapStop(uint256 _poolId, bool _swapStop) external;

    function setWeightForChainPath(
        uint256 _poolId,
        uint16 _dstChainId,
        uint256 _dstPoolId,
        uint16 _weight
    ) external;

    function swap(
        uint16 _dstChainId,
        uint256 _srcPoolId,
        uint256 _dstPoolId,
        address _refundAddress,
        uint256 _amountLD,
        uint256 _minAmountLD,
        IStargateRouter.lzTxObj memory _lzTxParams,
        bytes memory _to,
        bytes memory _payload
    ) external payable;

    function swapRemote(
        uint16 _srcChainId,
        bytes memory _srcAddress,
        uint256 _nonce,
        uint256 _srcPoolId,
        uint256 _dstPoolId,
        uint256 _dstGasForCall,
        address _to,
        Pool.SwapObj memory _s,
        bytes memory _payload
    ) external;

    function transferOwnership(address newOwner) external;

    function withdrawMintFee(uint256 _poolId, address _to) external;

    function withdrawProtocolFee(uint256 _poolId, address _to) external;
}

interface Pool {
    struct CreditObj {
        uint256 credits;
        uint256 idealBalance;
    }

    struct SwapObj {
        uint256 amount;
        uint256 eqFee;
        uint256 eqReward;
        uint256 lpFee;
        uint256 protocolFee;
        uint256 lkbRemove;
    }
}

interface IStargateRouter {
    struct lzTxObj {
        uint256 dstGasForCall;
        uint256 dstNativeAmount;
        bytes dstNativeAddr;
    }
}